WIP: tests for lib
monero-ecosystem/monero-rpc-rs pull request #65
Opened 2022-07-12 23:58 UTC by LeoNero

2022-07-27 20:01 UTC, TheCharlatan commented on tests/rpc.rs
> +    let rpc_client = monero_rpc::RpcClient::new("http://node.monerooutreach.org:18081".to_string());
This test is overkill, it cannot enforce that it catches any changes to the README example and always fails if the public node is down (like right now). Please remove this one.

2022-07-27 20:10 UTC, TheCharlatan commented on tests/common/helpers/daemon_rpc.rs
> +use monero::cryptonote::hash::Hash;
What is the purpose of the `common` directory? Seems to me like you could move everything one directory level up and remove the `common` dir.

2022-07-27 20:24 UTC, LeoNero commented on tests/common/helpers/daemon_rpc.rs
> +use monero::cryptonote::hash::Hash;
The `common` dir (and any other folder in `tests/` with a `mod.rs`) does not compile as a separate crate and also it does not not appear in the test results, which makes sense since it does not test anything (https://doc.rust-lang.org/book/ch11-03-test-organization.html#submodules-in-integration-tests)

2022-07-27 20:24 UTC, LeoNero commented on tests/common/helpers/daemon_rpc.rs
> +use monero::cryptonote::hash::Hash;
Or you mean removing the common dir but having the `helpers` dir?

2022-07-27 20:39 UTC, LeoNero commented on tests/rpc.rs
> +    let rpc_client = monero_rpc::RpcClient::new("http://node.monerooutreach.org:18081".to_string());
We can find another solution later. For example, see the end of https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#include-items-only-when-collecting-doctests

2022-07-27 20:39 UTC, TheCharlatan commented on tests/common/helpers/daemon_rpc.rs
> +use monero::cryptonote::hash::Hash;
> Or you mean removing the common dir but having the helpers and main_tests dir?

Yes, that :)

2022-07-27 20:40 UTC, TheCharlatan commented on tests/common/helpers/wallet.rs
> +    let wallet_err = create_wallet(wallet, None, ":thinking_face".to_string())
:thinking:

2022-07-27 20:51 UTC, TheCharlatan requested changes

2022-07-27 20:51 UTC, TheCharlatan commented on tests/common/main_tests/all_clients_interaction.rs
> +use std::collections::HashMap;
I don't like the `main_tests` directory. It does not accurately describe what is being tested (there is no `main` function) and the function exporting muddies things a bit for me. Either put all the files in here in `tests/` or put them all in one file. The `test` functions should also be renamed to their actual names in my opinion.

2022-07-27 20:51 UTC, TheCharlatan commented on tests/common/main_tests/all_clients_interaction.rs
> +    // note the order of the following two `refresh` is important
why?

2022-07-27 20:51 UTC, TheCharlatan commented on tests/rpc.rs
> +    let handle1 = tokio::spawn(main_tests::basic_wallet_test());
Please add some explanation for each of these test functions. What is their broad purpose and why are they grouped the way they are? What is the difference between each of them? Why does the clients interaction test have to be run separately?

2022-07-27 20:58 UTC, TheCharlatan commented on tests/common/helpers/wallet.rs
> +    assert_eq!(version, (1, 25));
Surface the expected version to the caller.

2022-07-27 21:13 UTC, TheCharlatan commented on tests/common/main_tests/basic_wallet.rs
> +    helpers::wallet::get_address_index(
By the function's name it is unclear what happens with the passed in Index. Can you think of a good rename for all functions that test their results against passed in expected values? Maybe add a suffix along the lines of `_assert_index`. 

In javascript testing I like to use objects as arguments, so I can explicitly name the args that are used as expected results. Doing this in Rust is too verbose and not ergonomic, so we have stick with too long function names for now.

2022-07-27 21:16 UTC, TheCharlatan commented on tests/common/helpers/wallet.rs
> +    expected_res: AddressData,
There is a naming consistency issue here. Either name all of the expected data `expected_res` or explicitly mention their type or purpose again, like in `expected_index`.

2022-07-27 21:22 UTC, TheCharlatan commented on tests/common/helpers/regtest.rs
> +async fn get_expected_height_returned_by_generate_blocks(
No need to make this async.

2022-07-28 21:42 UTC, LeoNero commented on tests/common/helpers/daemon_rpc.rs
> +use monero::cryptonote::hash::Hash;
I think it makes sense to remove the `common` dir, and put the `helpers` dir inside `main_tests` (which is going to be renamed)

2022-07-28 22:29 UTC, LeoNero commented on tests/common/main_tests/all_clients_interaction.rs
> +use std::collections::HashMap;
For the first suggestion: putting all files in `tests/` would run each test as isolated tests; but this is not good because they interact with the same RPC clients, and some tests depend on what changes were and were not made by other tests.

For the second suggestion: putting them all in one file would made the `rpc.rs` file really big. I changed to separate folders/files because of that.

The the last suggestion, I thought about it in the beginning, but having, for example, `basic_wallet::basic_wallet as basic_wallet_test` would be weird. What do you think about creating renaming `main_tests` to `client_tests`, rename the `test` function to maybe `run`, and then `rpc.rs` could import the functions as e.g. `client_tests::basic_wallet::run()`. This gets rid of the renamings in `mod.rs` too.

2022-07-29 18:58 UTC, LeoNero commented on tests/common/main_tests/basic_wallet.rs
> +    helpers::wallet::get_address_index(
this is a bit difficult and the names will end up too long, but I think it makes sense

2022-07-29 19:27 UTC, LeoNero commented on tests/rpc.rs
> +    let rpc_client = monero_rpc::RpcClient::new("http://node.monerooutreach.org:18081".to_string());
I removed the commit for this one :)

2022-07-29 19:27 UTC, LeoNero commented on tests/common/helpers/daemon_rpc.rs
> +use monero::cryptonote::hash::Hash;
https://github.com/monero-ecosystem/monero-rpc-rs/pull/65/commits/1bf8292864a5d9219c7e2702ae31dba9d697e3b7

2022-07-29 19:28 UTC, LeoNero commented on tests/common/main_tests/all_clients_interaction.rs
> +use std::collections::HashMap;
https://github.com/monero-ecosystem/monero-rpc-rs/pull/65/commits/0c01add7b80e97d8ec7ac77930db4330d796a542

2022-07-29 19:28 UTC, LeoNero commented on tests/common/main_tests/all_clients_interaction.rs
> +    // note the order of the following two `refresh` is important
https://github.com/monero-ecosystem/monero-rpc-rs/pull/65/commits/c052b8e65be52e97297a0e93d09e37415e2c3b1d

2022-07-29 19:28 UTC, LeoNero commented on tests/rpc.rs
> +    let handle1 = tokio::spawn(main_tests::basic_wallet_test());
https://github.com/monero-ecosystem/monero-rpc-rs/pull/65/commits/c052b8e65be52e97297a0e93d09e37415e2c3b1d

2022-07-29 19:30 UTC, LeoNero commented on tests/common/helpers/wallet.rs
> +    assert_eq!(version, (1, 25));
https://github.com/monero-ecosystem/monero-rpc-rs/pull/65/commits/eacb6a2ed84224a31f6318c7dcf55493dcdf4626#diff-36095b24c9882c3e8854cf445a782d14f0e64dfc66345e426988c5b3260794aeL24

2022-07-29 19:31 UTC, LeoNero commented on tests/common/main_tests/basic_wallet.rs
> +    helpers::wallet::get_address_index(
https://github.com/monero-ecosystem/monero-rpc-rs/pull/65/commits/7114e05f86f48641adb2f037ba63648b75e7a9cb

2022-07-29 19:31 UTC, LeoNero commented on tests/common/helpers/wallet.rs
> +    expected_res: AddressData,
https://github.com/monero-ecosystem/monero-rpc-rs/pull/65/commits/f22109bd55b0123febabfbe499eee4842eaa2526

2022-07-29 19:31 UTC, LeoNero commented on tests/common/helpers/regtest.rs
> +async fn get_expected_height_returned_by_generate_blocks(
https://github.com/monero-ecosystem/monero-rpc-rs/pull/65/commits/eacb6a2ed84224a31f6318c7dcf55493dcdf4626

2022-07-29 20:51 UTC, TheCharlatan commented on tests/rpc.rs
> +     *    in ways the other tests do not (for example, it creates transacions), aand it also creates
Just one tiny typo fix: aand

2022-07-29 20:53 UTC, LeoNero commented on tests/rpc.rs
> +     *    in ways the other tests do not (for example, it creates transacions), aand it also creates
done

2022-07-29 20:54 UTC, TheCharlatan approved these changes

2022-07-29 21:03 UTC, merged